login_app/urls.py
from django.urls import path
from . import views


app_name = 'login_app'

urlpatterns = [
        path('login/', views.login, name='login'),
        path('logout/', views.logout, name='logout'),
        path('sign_up/', views.sign_up, name='sign_up'),
        path('delete_account/', views.delete_account, name='delete_account')
        ]

todo_app/urls.py
from django.shortcuts import render
from django.urls import path

from . import views

app_name = 'todo_app'

urlpatterns = [
           path('', views.index, name='index'),
           path('change_status', views.change_status, name='change_status'),
           path('completed_todos/', views.completed_todos, name='completed_todos'),
           path('delete_todo/', views.delete_todo, name='delete_todo'),
]

todo_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo_app.urls')),
    path('accounts/', include('login_app.urls')),
]

login_app/models.py
from django.db import models

# Create your models here.

todo_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    done = models.BooleanField(default=False)
   # priority = models.IntegerField(unique=True)

    #class Meta:
     #   order_by = 'priority'

      #  def highest_priority():
       #     Todo.objects.last()

    def __str__(self):
        return f'{self.pk}: user: {self.user}, text: "{self.text}" done: {self.done}'
# Create your models here.

user_profile_app/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=25, blank=True)

    def __str__(self):
        return self.user.username

login_app/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect

def login(request):
    context = {}

    if request.method == "POST":
        user = authenticate(request, username=request.POST['user_name'], password=request.POST['password'])
        if user:
            dj_login(request, user)
            return HttpResponseRedirect(reverse('todo_app:index'))
        else:
            context = {
                    'error': 'Bad username of password'
                    }
    return render(request, 'login_app/login.html', context)

def logout(request):
    dj_logout(request)
    return HttpResponseRedirect(reverse('login_app:login'))

def sign_up(request):
    context = {}
    if request.method == 'POST':
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        user_name = request.POST['user_name']
        email = request.POST['email']
        if password != confirm_password:
            context = {'error': 'Passwords do not match'}
        else:
            if User.objects.create_user(user_name, email, password):
                return HttpResponseRedirect(reverse('login_app:login'))
            else:
                context = {
                        'error':'Could not create the user account - please try again'
                        }
    return render(request, 'login_app/sign_up.html', context)

@login_required
def delete_account(request):
    if request.method == "POST":
        if request.POST['confirm_deletion'] == "DELETE":
            user = authenticate(request, username=request.user.username, password=request.POST['password'])
            if user:
                print(f"Deleting user {user}")
                user.delete()
                return HttpResponseRedirect(reverse('login_app:login'))
            else:
                print("Could not delete the account")
    return render(request, 'login_app/delete_account.html')

todo_app/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Todo

@login_required
def index(request):

    if request.method == "POST":
            text = request.POST["text"]
            todo = Todo()
            todo.user = request.user
            todo.text = text
            todo.save()

    todos = Todo.objects.filter(user=request.user, done=False)
    context = {
        'todos': todos
    }

    return render(request, 'todo_app/index.html', context)

@login_required
def change_status(request):
  pk = request.POST['pk']
  todo = get_object_or_404(Todo, user=request.user, pk=pk)
  if "checked" in request.POST:
      todo.done = True
  else:
      todo.done = False
  todo.save()
  return HttpResponseRedirect(reverse('todo_app:index'))

@login_required
def completed_todos(request):
    todos = Todo.objects.filter(done=True)
    context = {
        'todos':todos,
    }
    return render(request, 'todo_app/completed_todos.html', context)

@login_required
def delete_todo(request):
    print(request.META['HTTP_REFERER'])
    pk = request.POST['pk']
    todo = get_object_or_404(Todo, user=request.user, pk=pk)
    todo.delete()
    if request.META['HTTP_REFERER'].split('/')[-2] == 'todo':
        return HttpResponseRedirect(reverse('todo_app:index'))
    else:
        return HttpResponseRedirect(reverse('todo_app:completed_todos'))

# Create your views here.

user_profile_app/views.py
from django.shortcuts import render

# Create your views here.

login_app/templates/login_app/delete_account.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Delete Account</title>
</head>
<body>
    <h1>Delete Account: {{ user }}</h1>
   <hr />
   <form action="{% url 'login_app:delete_account'%}" method="POST">
      {% csrf_token %}
      <input type="password" name="password" placeholder="Password">
      <br />
      <input type="text" name="confirm_deletion" placeholder="TYPE DELETE">
      <br />
      <button>Submit</button>
   </form>
   <hr />
</body>
</html>

login_app/templates/login_app/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Login</title>
    </head>
    <body>
        <h1>Login</h1>
        <hr />
        <form action="{% url 'login_app:login' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="user_name" placeholder="User Name">
            <input type="password" name="password" placeholder="Password">
            <button>Login</button>
        </form>
        <hr />
        {% if error %}
        {{ error }}
        {% endif %}
    </body>
</html>

login_app/templates/login_app/sign_up.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Sign Up</title>
    </head>
    <body>
        <h1>Sign Up</h1>
        <hr />
        <form action="{% url 'login_app:sign_up' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="user_name" placeholder="User Name">
            <input type="email" name="email" placeholder="Email Address">
            <input type="password" name="password" placeholder="Password">
            <input type="password" name="confirm_password" placeholder="Confirm Password">
            <button>Sign Up</button>
        </form>
        <hr />
        {% if error %}
        {{ error }}
        {% endif %}
    </body>
</html>

todo_app/templates/todo_app/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% block title %}
        {% endblock %}
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'todo_app/todo_app.css' %}" media="screen" />
    </head>
    <body>
        <header>

            <h1>Todo</h1>
        </header>
        <hr />
        {% block content %}
        {% endblock %}
    </body>
</html>

todo_app/templates/todo_app/completed_todos.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Completed Todos</title>
    </head>
    <body>
        <h1>Completed Todo</h1>
        <hr />
        <ul>
            {% for todo in todos  %}
            <li>
                <form action="{% url 'todo_app:change_status' %}" method="POST">
                    {% csrf_token %}
                    <input type="checkbox" name="checked" {% if todo.done %}checked{% endif %} >
                    <button formaction="{% url 'todo_app:delete_todo' %}">Delete</button>
                    <button>Update</button>
                    <input type="hidden" name="pk" value="{{ todo.pk }}">
                    {{ todo.text }}
                </form>
            </li>
            {% endfor %}
        </ul>
        <hr />
        <a href="{% url 'todo_app:index' %}">Todos</a>
    </body>
</html>

todo_app/templates/todo_app/index.html
{% extends "./base.html" %}



{% block content %}

{% block title %}<title>Todo</title>{% endblock  %}

<p>Welcome {{ user }} - <a href="{% url 'login_app:logout' %}">Log out</a> - <a href="{% url 'login_app:delete_account' %}" >Delete Account</a></p>
<ul>
    {% for todo in todos  %}
    <li>
        <form action="{% url 'todo_app:change_status' %}" method="POST">
            {% csrf_token %}
            <input type="checkbox" name="checked" {% if todo.done %}checked{% endif %} >
            <button>Update</button>
            <button formaction="{% url 'todo_app:delete_todo' %}">Delete</button>
            <input type="hidden" name="pk" value="{{ todo.pk }}">
            {{ todo.text }}
        </form>
    </li>
    {% endfor  %}
</ul>
<hr />
<form action="." method="POST">
    {% csrf_token %}
    <input type="text" name="text" placeholder="Write your todo item here!" />
    <button>Create todo</button>
</form>
<a href="{% url 'todo_app:completed_todos' %}">Completed todos</a>
{% endblock %}